# Generated by Django 4.2.7 on 2023-11-03 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('site_attrs', models.CharField(max_length=512)),
                ('user_site_name', models.CharField(max_length=64)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RedirectHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_date', models.DateTimeField()),
                ('data_request_bytes', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('data_response_bytes', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_history', to='services.link')),
            ],
        ),
    ]
