# Generated by Django 4.2.7 on 2023-11-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirecthistory',
            name='enter_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
